In [2]:
import pandas as pd
import numpy as np

# librerías de visualización
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Demography

In [41]:
# cargamos el dataset
df_demo = pd.read_excel("../data/raw_data/Telco_customer_churn_demographics.xlsx")
df_demo.head()

Customer ID  Count  Gender  Age Under 30 Senior Citizen Married Dependents  \
0  8779-QRDMV      1    Male   78       No            Yes      No         No   
1  7495-OOKFY      1  Female   74       No            Yes     Yes        Yes   
2  1658-BYGOY      1    Male   71       No            Yes      No        Yes   
3  4598-XLKNJ      1  Female   78       No            Yes     Yes        Yes   
4  4846-WHAFZ      1  Female   80       No            Yes     Yes        Yes   

   Number of Dependents  
0                     0  
1                     1  
2                     3  
3                     1  
4                     1

In [42]:
df_demo.drop(columns=["Under 30","Senior Citizen","Count"], axis=1, inplace=True)

In [43]:
df_demo.isnull().sum()

Customer ID             0
Gender                  0
Age                     0
Married                 0
Dependents              0
Number of Dependents    0
dtype: int64

In [44]:
df_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Customer ID           7043 non-null   object
 1   Gender                7043 non-null   object
 2   Age                   7043 non-null   int64 
 3   Married               7043 non-null   object
 4   Dependents            7043 non-null   object
 5   Number of Dependents  7043 non-null   int64 
dtypes: int64(2), object(4)
memory usage: 330.3+ KB


In [45]:
df_demo.head()

Customer ID  Gender  Age Married Dependents  Number of Dependents
0  8779-QRDMV    Male   78      No         No                     0
1  7495-OOKFY  Female   74     Yes        Yes                     1
2  1658-BYGOY    Male   71      No        Yes                     3
3  4598-XLKNJ  Female   78     Yes        Yes                     1
4  4846-WHAFZ  Female   80     Yes        Yes                     1

In [121]:
#SQL
df_demo.to_csv('../data/SQL/df_demo.csv', index=False)

- ML

In [84]:
df_demo_m= df_demo.copy()

In [86]:
df_demo_m.drop(columns=["Dependents"], axis=1, inplace=True)

In [87]:
df_demo_m.head(1)

Customer ID Gender  Age Married  Number of Dependents
0  8779-QRDMV   Male   78      No                     0

# Localization

In [127]:
df_loc = pd.read_excel("../data/raw_data/Telco_customer_churn_location.xlsx")
df_loc.head()

Customer ID  Count        Country       State         City  Zip Code  \
0  8779-QRDMV      1  United States  California  Los Angeles     90022   
1  7495-OOKFY      1  United States  California  Los Angeles     90063   
2  1658-BYGOY      1  United States  California  Los Angeles     90065   
3  4598-XLKNJ      1  United States  California    Inglewood     90303   
4  4846-WHAFZ      1  United States  California     Whittier     90602   

                 Lat Long   Latitude   Longitude  
0   34.02381, -118.156582  34.023810 -118.156582  
1  34.044271, -118.185237  34.044271 -118.185237  
2  34.108833, -118.229715  34.108833 -118.229715  
3  33.936291, -118.332639  33.936291 -118.332639  
4  33.972119, -118.020188  33.972119 -118.020188

In [16]:
df_loc["Count"].unique()

array([1])

In [17]:
df_loc["Country"].unique()

array(['United States'], dtype=object)

In [18]:
df_loc["State"].unique()

array(['California'], dtype=object)

In [19]:
df_loc["City"].unique()

array(['Los Angeles', 'Inglewood', 'Whittier', ..., 'Topaz', 'Jacumba',
       'Holtville'], dtype=object)

In [128]:
df_loc.drop(columns=["Country","State","Lat Long","Count"], axis=1, inplace=True)

In [129]:
df_loc.head()

Customer ID         City  Zip Code   Latitude   Longitude
0  8779-QRDMV  Los Angeles     90022  34.023810 -118.156582
1  7495-OOKFY  Los Angeles     90063  34.044271 -118.185237
2  1658-BYGOY  Los Angeles     90065  34.108833 -118.229715
3  4598-XLKNJ    Inglewood     90303  33.936291 -118.332639
4  4846-WHAFZ     Whittier     90602  33.972119 -118.020188

In [130]:
#Tableau 
df_loc.to_csv('../data/Tableau/df_loc.csv', index=False)

In [ ]:
# SQL

In [131]:
df_loc_sql=df_loc.copy()
df_loc_sql.drop(columns=["Latitude","Longitude"], axis=1, inplace=True)

In [132]:
df_loc_sql.head(1)

Customer ID         City  Zip Code
0  8779-QRDMV  Los Angeles     90022

In [140]:
#SQL
df_loc_sql.to_csv('../data/SQL/df_localization.csv', index=False)

# Population

In [134]:
df_pop = pd.read_excel("../data/raw_data/Telco_customer_churn_population.xlsx")
df_pop.head()

ID  Zip Code  Population
0   1     90001       54492
1   2     90002       44586
2   3     90003       58198
3   4     90004       67852
4   5     90005       43019

In [135]:
df_pop.drop(columns=["ID"], axis=1, inplace=True)

In [136]:
df_pop.head(1)

Zip Code  Population
0     90001       54492

In [152]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Zip Code    1671 non-null   int64
 1   Population  1671 non-null   int64
dtypes: int64(2)
memory usage: 26.2 KB


In [137]:
#SQL
df_pop.to_csv('../data/SQL/df_pop.csv', index=False)

In [138]:
df_loc_pop = pd.merge(df_loc, df_pop, on='Zip Code')

In [139]:
df_loc_pop.head()

Customer ID         City  Zip Code  Latitude   Longitude  Population
0  8779-QRDMV  Los Angeles     90022  34.02381 -118.156582       68701
1  4737-AQCPU  Los Angeles     90022  34.02381 -118.156582       68701
2  5043-TRZWM  Los Angeles     90022  34.02381 -118.156582       68701
3  8165-CBKXO  Los Angeles     90022  34.02381 -118.156582       68701
4  9979-RGMZT  Los Angeles     90022  34.02381 -118.156582       68701

In [32]:
df_loc_pop.drop(columns=["ID","Zip Code"], axis=1, inplace=True)

In [33]:
df_loc_pop.head(1)

Customer ID         City  Population
0  8779-QRDMV  Los Angeles       68701

In [36]:
#SQL
df_loc_pop.to_csv('../data/SQL/df_loc.csv', index=False)

In [88]:
df_loc_pop.head(1)

Customer ID         City  Population
0  8779-QRDMV  Los Angeles       68701

In [33]:
df_demo.head()

In [89]:
df_final = pd.merge(df_demo_m, df_loc_pop, on='Customer ID')


In [90]:
df_final.head()

Customer ID  Gender  Age Married  Number of Dependents         City  \
0  8779-QRDMV    Male   78      No                     0  Los Angeles   
1  7495-OOKFY  Female   74     Yes                     1  Los Angeles   
2  1658-BYGOY    Male   71      No                     3  Los Angeles   
3  4598-XLKNJ  Female   78     Yes                     1    Inglewood   
4  4846-WHAFZ  Female   80     Yes                     1     Whittier   

   Population  
0       68701  
1       55668  
2       47534  
3       27778  
4       26265

# Services

In [141]:
df_services = pd.read_excel("../data/raw_data/Telco_customer_churn_services.xlsx")
df_services.head()

Customer ID  Count Quarter Referred a Friend  Number of Referrals  \
0  8779-QRDMV      1      Q3                No                    0   
1  7495-OOKFY      1      Q3               Yes                    1   
2  1658-BYGOY      1      Q3                No                    0   
3  4598-XLKNJ      1      Q3               Yes                    1   
4  4846-WHAFZ      1      Q3               Yes                    1   

   Tenure in Months    Offer Phone Service  Avg Monthly Long Distance Charges  \
0                 1     None            No                               0.00   
1                 8  Offer E           Yes                              48.85   
2                18  Offer D           Yes                              11.33   
3                25  Offer C           Yes                              19.76   
4                37  Offer C           Yes                               6.33   

  Multiple Lines  ... Unlimited Data        Contract  Paperless Billing  \
0             No  ...             No  Month-to-Month                Yes   
1            Yes  ...            Yes  Month-to-Month                Yes   
2            Yes  ...            Yes  Month-to-Month                Yes   
3             No  ...            Yes  Month-to-Month                Yes   
4            Yes  ...            Yes  Month-to-Month                Yes   

    Payment Method Monthly Charge Total Charges Total Refunds  \
0  Bank Withdrawal          39.65         39.65          0.00   
1      Credit Card          80.65        633.30          0.00   
2  Bank Withdrawal          95.45       1752.55         45.61   
3  Bank Withdrawal          98.50       2514.50         13.43   
4  Bank Withdrawal          76.50       2868.15          0.00   

  Total Extra Data Charges Total Long Distance Charges Total Revenue  
0                       20                        0.00         59.65  
1                        0                      390.80       1024.10  
2                        0                      203.94       1910.88  
3                        0                      494.00       2995.07  
4                        0                      234.21       3102.36  

[5 rows x 30 columns]

- SQL

In [142]:
df_services.drop(columns=["Count","Quarter"], axis=1, inplace=True)

In [60]:
df_services["Paperless Billing"].unique()

array(['Yes', 'No'], dtype=object)

In [61]:
df_services["Offer"].unique()

array(['None', 'Offer E', 'Offer D', 'Offer C', 'Offer B', 'Offer A'],
      dtype=object)

In [143]:
df_services.head(2)

Customer ID Referred a Friend  Number of Referrals  Tenure in Months  \
0  8779-QRDMV                No                    0                 1   
1  7495-OOKFY               Yes                    1                 8   

     Offer Phone Service  Avg Monthly Long Distance Charges Multiple Lines  \
0     None            No                               0.00             No   
1  Offer E           Yes                              48.85            Yes   

  Internet Service Internet Type  ...  Unlimited Data        Contract  \
0              Yes           DSL  ...              No  Month-to-Month   
1              Yes   Fiber Optic  ...             Yes  Month-to-Month   

  Paperless Billing   Payment Method Monthly Charge Total Charges  \
0               Yes  Bank Withdrawal          39.65         39.65   
1               Yes      Credit Card          80.65        633.30   

  Total Refunds Total Extra Data Charges Total Long Distance Charges  \
0           0.0                       20                         0.0   
1           0.0                        0                       390.8   

  Total Revenue  
0         59.65  
1       1024.10  

[2 rows x 28 columns]

In [58]:
df_services["Contract"].unique()

array(['Month-to-Month', 'One Year', 'Two Year'], dtype=object)

In [72]:
df_services["Total Extra Data Charges"].unique()

array([ 20,   0,  10, 120, 140,  90,  80,  30, 100,  40, 110, 150,  70,
        50, 130,  60])

In [75]:
df_services["Tenure in Months"].unique()

array([ 1,  8, 18, 25, 37, 27, 58, 15,  7, 11,  3, 13, 16, 24,  4, 32, 54,
        2, 21, 55,  5, 20, 65, 49, 43, 56, 52, 33, 30, 46,  9, 10, 35, 44,
       62, 14, 12, 17, 39, 68, 34, 22, 19, 23, 42, 41, 57, 38, 29, 66, 69,
       40, 31, 59, 36, 45, 53, 70, 47, 50, 51, 72, 26,  6, 28, 48, 61, 71,
       60, 64, 67, 63])

In [144]:
df_services.columns

Index(['Customer ID', 'Referred a Friend', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue'],
      dtype='object')

In [157]:
df_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 28 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Customer ID                        7043 non-null   object 
 1   Referred a Friend                  7043 non-null   object 
 2   Number of Referrals                7043 non-null   int64  
 3   Tenure in Months                   7043 non-null   int64  
 4   Offer                              7043 non-null   object 
 5   Phone Service                      7043 non-null   object 
 6   Avg Monthly Long Distance Charges  7043 non-null   float64
 7   Multiple Lines                     7043 non-null   object 
 8   Internet Service                   7043 non-null   object 
 9   Internet Type                      7043 non-null   object 
 10  Avg Monthly GB Download            7043 non-null   int64  
 11  Online Security                    7043 non-null   objec

In [145]:
#SQL
df_services.to_csv('../data/SQL/df_services.csv', index=False)

- ML 

In [92]:
df_services_m=df_services.copy()

In [95]:
df_services_m.head(1)

Customer ID Referred a Friend  Number of Referrals  Tenure in Months Offer  \
0  8779-QRDMV                No                    0                 1  None   

  Phone Service  Avg Monthly Long Distance Charges Multiple Lines  \
0            No                                0.0             No   

  Internet Service Internet Type  ...  Unlimited Data        Contract  \
0              Yes           DSL  ...              No  Month-to-Month   

  Paperless Billing   Payment Method Monthly Charge Total Charges  \
0               Yes  Bank Withdrawal          39.65         39.65   

  Total Refunds Total Extra Data Charges Total Long Distance Charges  \
0           0.0                       20                         0.0   

  Total Revenue  
0         59.65  

[1 rows x 28 columns]

In [97]:
df_services_m.columns

Index(['Customer ID', 'Referred a Friend', 'Number of Referrals',
       'Tenure in Months', 'Offer', 'Phone Service',
       'Avg Monthly Long Distance Charges', 'Multiple Lines',
       'Internet Service', 'Internet Type', 'Avg Monthly GB Download',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds',
       'Total Extra Data Charges', 'Total Long Distance Charges',
       'Total Revenue'],
      dtype='object')

In [103]:
df_services_m["Total Extra Data Charges"].unique()

array([ 20,   0,  10, 120, 140,  90,  80,  30, 100,  40, 110, 150,  70,
        50, 130,  60])

In [105]:
df_services_m.drop(columns=["Referred a Friend"], axis=1, inplace=True)

In [107]:
df_services_m.head()

Customer ID  Number of Referrals  Tenure in Months    Offer Phone Service  \
0  8779-QRDMV                    0                 1     None            No   
1  7495-OOKFY                    1                 8  Offer E           Yes   
2  1658-BYGOY                    0                18  Offer D           Yes   
3  4598-XLKNJ                    1                25  Offer C           Yes   
4  4846-WHAFZ                    1                37  Offer C           Yes   

   Avg Monthly Long Distance Charges Multiple Lines Internet Service  \
0                               0.00             No              Yes   
1                              48.85            Yes              Yes   
2                              11.33            Yes              Yes   
3                              19.76             No              Yes   
4                               6.33            Yes              Yes   

  Internet Type  Avg Monthly GB Download  ... Unlimited Data        Contract  \
0           DSL                        8  ...             No  Month-to-Month   
1   Fiber Optic                       17  ...            Yes  Month-to-Month   
2   Fiber Optic                       52  ...            Yes  Month-to-Month   
3   Fiber Optic                       12  ...            Yes  Month-to-Month   
4   Fiber Optic                       14  ...            Yes  Month-to-Month   

  Paperless Billing   Payment Method Monthly Charge Total Charges  \
0               Yes  Bank Withdrawal          39.65         39.65   
1               Yes      Credit Card          80.65        633.30   
2               Yes  Bank Withdrawal          95.45       1752.55   
3               Yes  Bank Withdrawal          98.50       2514.50   
4               Yes  Bank Withdrawal          76.50       2868.15   

  Total Refunds Total Extra Data Charges Total Long Distance Charges  \
0          0.00                       20                        0.00   
1          0.00                        0                      390.80   
2         45.61                        0                      203.94   
3         13.43                        0                      494.00   
4          0.00                        0                      234.21   

  Total Revenue  
0         59.65  
1       1024.10  
2       1910.88  
3       2995.07  
4       3102.36  

[5 rows x 27 columns]

In [108]:
df_final = pd.merge(df_final, df_services_m, on='Customer ID')


In [109]:
df_final.head(1)

Customer ID Gender  Age Married  Number of Dependents         City  \
0  8779-QRDMV   Male   78      No                     0  Los Angeles   

   Population  Number of Referrals  Tenure in Months Offer  ...  \
0       68701                    0                 1  None  ...   

  Unlimited Data        Contract Paperless Billing   Payment Method  \
0             No  Month-to-Month               Yes  Bank Withdrawal   

  Monthly Charge  Total Charges Total Refunds Total Extra Data Charges  \
0          39.65          39.65           0.0                       20   

  Total Long Distance Charges Total Revenue  
0                         0.0         59.65  

[1 rows x 33 columns]

- Tableau

# Status

In [146]:
df_status = pd.read_excel("../data/raw_data/Telco_customer_churn_status.xlsx")
df_status.head()

Customer ID  Count Quarter  Satisfaction Score Customer Status Churn Label  \
0  8779-QRDMV      1      Q3                   3         Churned         Yes   
1  7495-OOKFY      1      Q3                   3         Churned         Yes   
2  1658-BYGOY      1      Q3                   2         Churned         Yes   
3  4598-XLKNJ      1      Q3                   2         Churned         Yes   
4  4846-WHAFZ      1      Q3                   2         Churned         Yes   

   Churn Value  Churn Score  CLTV   Churn Category  \
0            1           91  5433       Competitor   
1            1           69  5302       Competitor   
2            1           81  3179       Competitor   
3            1           88  5337  Dissatisfaction   
4            1           67  2793            Price   

                   Churn Reason  
0  Competitor offered more data  
1  Competitor made better offer  
2  Competitor made better offer  
3     Limited range of services  
4            Extra data charges

In [55]:
df_status["Quarter"].unique()

array(['Q3'], dtype=object)

In [147]:
df_status.drop(columns=["Quarter","Count"], axis=1, inplace=True)

In [149]:
df_status.head(1)

Customer ID  Satisfaction Score Customer Status Churn Label  Churn Value  \
0  8779-QRDMV                   3         Churned         Yes            1   

   Churn Score  CLTV Churn Category                  Churn Reason  
0           91  5433     Competitor  Competitor offered more data

In [150]:
df_status.isnull().sum()

Customer ID              0
Satisfaction Score       0
Customer Status          0
Churn Label              0
Churn Value              0
Churn Score              0
CLTV                     0
Churn Category        5174
Churn Reason          5174
dtype: int64

In [158]:
df_status.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Customer ID         7043 non-null   object
 1   Satisfaction Score  7043 non-null   int64 
 2   Customer Status     7043 non-null   object
 3   Churn Label         7043 non-null   object
 4   Churn Value         7043 non-null   int64 
 5   Churn Score         7043 non-null   int64 
 6   CLTV                7043 non-null   int64 
 7   Churn Category      1869 non-null   object
 8   Churn Reason        1869 non-null   object
dtypes: int64(4), object(5)
memory usage: 495.3+ KB


In [151]:
#SQL
df_status.to_csv('../data/SQL/df_status.csv', index=False)

- ML

In [113]:
df_status_m= df_status.copy()

In [114]:
df_status_m.drop(columns=["Churn Label"], axis=1, inplace=True)

In [115]:
df_status_m.head()

Customer ID  Satisfaction Score Customer Status  Churn Value  Churn Score  \
0  8779-QRDMV                   3         Churned            1           91   
1  7495-OOKFY                   3         Churned            1           69   
2  1658-BYGOY                   2         Churned            1           81   
3  4598-XLKNJ                   2         Churned            1           88   
4  4846-WHAFZ                   2         Churned            1           67   

   CLTV   Churn Category                  Churn Reason  
0  5433       Competitor  Competitor offered more data  
1  5302       Competitor  Competitor made better offer  
2  3179       Competitor  Competitor made better offer  
3  5337  Dissatisfaction     Limited range of services  
4  2793            Price            Extra data charges

In [57]:
df_status["Churn Label"].unique()

array(['Yes', 'No'], dtype=object)

In [8]:
df_status.drop(columns=["Quarter","Churn Label"], axis=1, inplace=True)

In [10]:
df_status["Satisfaction Score"].unique()

array([3, 2, 1, 4, 5])

In [11]:
df_status["Customer Status"].unique()

array(['Churned', 'Stayed', 'Joined'], dtype=object)

In [4]:
df_status["Churn Value"].unique()

array([1, 0])

In [5]:
df_status["Churn Category"].unique()

array(['Competitor', 'Dissatisfaction', 'Price', 'Other', 'Attitude', nan],
      dtype=object)

In [7]:
df_status["Churn Score"].unique()

array([91, 69, 81, 88, 67, 95, 76, 85, 86, 65, 96, 84, 80, 73, 83, 90, 89,
       87, 82, 74, 66, 92, 72, 70, 94, 68, 75, 93, 77, 79, 71, 78, 38, 40,
       52, 25, 59, 21, 55, 60, 28,  8,  7, 50, 36, 23, 41, 34, 26, 56, 44,
       30, 62, 24, 47, 22, 32, 64, 27, 29, 54, 39, 45, 33, 58, 35, 20, 31,
       61, 49, 37, 63, 48, 57, 42, 53, 46, 43, 51,  9,  5])

In [6]:
df_status["Churn Reason"].unique()

array(['Competitor offered more data', 'Competitor made better offer',
       'Limited range of services', 'Extra data charges',
       'Competitor had better devices', "Don't know",
       'Service dissatisfaction',
       'Lack of affordable download/upload speed',
       'Product dissatisfaction', 'Long distance charges',
       'Poor expertise of online support', 'Attitude of support person',
       'Network reliability', 'Competitor offered higher download speeds',
       'Moved', 'Price too high', 'Attitude of service provider',
       'Poor expertise of phone support', 'Deceased', nan,
       'Lack of self-service on Website'], dtype=object)

In [9]:
df_status.head(2)

Customer ID  Count  Satisfaction Score Customer Status  Churn Value  \
0  8779-QRDMV      1                   3         Churned            1   
1  7495-OOKFY      1                   3         Churned            1   

   Churn Score  CLTV Churn Category                  Churn Reason  
0           91  5433     Competitor  Competitor offered more data  
1           69  5302     Competitor  Competitor made better offer

In [62]:
#SQL
df_status.to_csv('../data/SQL/df_status.csv', index=False)

In [116]:
df_final = pd.merge(df_final, df_status_m, on='Customer ID')

In [117]:
df_final.head()

Customer ID  Gender  Age Married  Number of Dependents         City  \
0  8779-QRDMV    Male   78      No                     0  Los Angeles   
1  7495-OOKFY  Female   74     Yes                     1  Los Angeles   
2  1658-BYGOY    Male   71      No                     3  Los Angeles   
3  4598-XLKNJ  Female   78     Yes                     1    Inglewood   
4  4846-WHAFZ  Female   80     Yes                     1     Whittier   

   Population  Number of Referrals  Tenure in Months    Offer  ...  \
0       68701                    0                 1     None  ...   
1       55668                    1                 8  Offer E  ...   
2       47534                    0                18  Offer D  ...   
3       27778                    1                25  Offer C  ...   
4       26265                    1                37  Offer C  ...   

  Total Extra Data Charges  Total Long Distance Charges Total Revenue  \
0                       20                         0.00         59.65   
1                        0                       390.80       1024.10   
2                        0                       203.94       1910.88   
3                        0                       494.00       2995.07   
4                        0                       234.21       3102.36   

  Satisfaction Score Customer Status  Churn Value Churn Score  CLTV  \
0                  3         Churned            1          91  5433   
1                  3         Churned            1          69  5302   
2                  2         Churned            1          81  3179   
3                  2         Churned            1          88  5337   
4                  2         Churned            1          67  2793   

    Churn Category                  Churn Reason  
0       Competitor  Competitor offered more data  
1       Competitor  Competitor made better offer  
2       Competitor  Competitor made better offer  
3  Dissatisfaction     Limited range of services  
4            Price            Extra data charges  

[5 rows x 40 columns]

In [118]:
#ML 

df_final.to_csv('../data/ML/df_final.csv', index=False)

# Churn xxxxxxx

In [64]:
df_churn = pd.read_excel("../data/raw_data/Telco_customer_churn.xlsx")
df_churn.head()

CustomerID  Count        Country       State         City  Zip Code  \
0  3668-QPYBK      1  United States  California  Los Angeles     90003   
1  9237-HQITU      1  United States  California  Los Angeles     90005   
2  9305-CDSKC      1  United States  California  Los Angeles     90006   
3  7892-POOKP      1  United States  California  Los Angeles     90010   
4  0280-XJGEX      1  United States  California  Los Angeles     90015   

                 Lat Long   Latitude   Longitude  Gender  ...        Contract  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...  Month-to-month   
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...  Month-to-month   
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...  Month-to-month   
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...  Month-to-month   
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...  Month-to-month   

  Paperless Billing             Payment Method  Monthly Charges Total Charges  \
0               Yes               Mailed check            53.85        108.15   
1               Yes           Electronic check            70.70        151.65   
2               Yes           Electronic check            99.65         820.5   
3               Yes           Electronic check           104.80       3046.05   
4               Yes  Bank transfer (automatic)           103.70        5036.3   

  Churn Label Churn Value Churn Score  CLTV                   Churn Reason  
0         Yes           1          86  3239   Competitor made better offer  
1         Yes           1          67  2701                          Moved  
2         Yes           1          86  5372                          Moved  
3         Yes           1          84  5003                          Moved  
4         Yes           1          89  5340  Competitor had better devices  

[5 rows x 33 columns]

In [65]:
df_churn.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')